services:
  electivote-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      HOST: ${HOST}
      PORT: ${PORT}
      SECRET_KEY: ${SECRET_KEY}
      SESSION_KEY: ${SESSION_KEY}
      COOKIE_KEY: ${COOKIE_KEY}
      DEBUG: ${DEBUG}
      GMAIL_EMAIL: ${GMAIL_EMAIL}
      GMAIL_PASSWORD: ${GMAIL_PASSWORD}
      OUTLOOK_EMAIL: ${OUTLOOK_EMAIL}
      OUTLOOK_PASSWORD: ${OUTLOOK_PASSWORD}
      REDIS_URL: ${REDIS_URL}
      SAWERIA_SECRET_KEY: ${SAWERIA_SECRET_KEY}
    depends_on:
      electivote-db:
        condition: service_healthy
      redis: 
        condition: service_healthy
    volumes:
      - .:/app  
      - ./internal/assets/images:/app/internal/assets/images  

  electivote-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER           
      MYSQL_PASSWORD: $DB_PASS   
      MYSQL_ROOT_PASSWORD: $DB_PASS
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  db_data:
